### ISSUE TITLE
Pass compiler options

### ISSUE THREAD

**Issue by cquiroz** [MaximeKjaer/scalajs-webpack-loader#1]
Would it be possible to pass compiler options. in particular (since I'm still on 0.6) I need to pass 
```
  scalacOptions += "-P:scalajs:sjsDefinedByDefault"
```

**Comment by MaximeKjaer** [comment]
Absolutely! I've implemented this in 4a154777d8caa0f74f7fd47b7624a5a3bd4f8655 and am releasing a version 0.0.4 with this feature right now.

**Comment by cquiroz** [comment]
Thanks for the quick respons, it is working great
